// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx5wWMV1xuxkmfFx5OkX70R_FiAoVPGFw',
    appId: '1:245171599369:web:cdc112e766f25d17cfa0d8',
    messagingSenderId: '245171599369',
    projectId: 'alu-connect-project',
    authDomain: 'alu-connect-project.firebaseapp.com',
    storageBucket: 'alu-connect-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzg-lJD-m7Km_ZZuF9Hw-vejSUjwzF2wE',
    appId: '1:245171599369:android:5d3a36edd10411b3cfa0d8',
    messagingSenderId: '245171599369',
    projectId: 'alu-connect-project',
    storageBucket: 'alu-connect-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx5wWMV1xuxkmfFx5OkX70R_FiAoVPGFw',
    appId: '1:245171599369:web:a51449f26011468acfa0d8',
    messagingSenderId: '245171599369',
    projectId: 'alu-connect-project',
    authDomain: 'alu-connect-project.firebaseapp.com',
    storageBucket: 'alu-connect-project.firebasestorage.app',
  );
}
